<?php

$resourcespace_mcp_annotations = [
    'do_search' => [
        'category' => 'search',
        'description' => 'Search resources by query, type, and archive state.',
        'synonyms' => ['find', 'query', 'lookup'],
        'readOnlyHint' => true,
        'destructiveHint' => false,
    ],
    'search_get_previews' => [
        'category' => 'search',
        'description' => 'Search resources and include requested preview URLs.',
        'synonyms' => ['preview', 'search', 'thumbnails'],
        'readOnlyHint' => true,
        'destructiveHint' => false,
    ],
    'get_dash_search_data' => [
        'category' => 'search',
        'description' => 'Return search data used by a dashboard tile.',
        'synonyms' => ['dash', 'tile', 'search'],
        'readOnlyHint' => true,
        'destructiveHint' => false,
    ],
    'create_resource' => [
        'category' => 'resources',
        'description' => 'Create a resource, optionally uploading from a URL and setting metadata.',
        'synonyms' => ['upload', 'new', 'asset'],
        'readOnlyHint' => false,
        'destructiveHint' => false,
    ],
    'get_resource_data' => [
        'category' => 'resources',
        'description' => 'Get the resource table record after access checks.',
        'synonyms' => ['metadata', 'asset', 'record'],
        'readOnlyHint' => true,
        'destructiveHint' => false,
    ],
    'get_resource_field_data' => [
        'category' => 'resources',
        'description' => 'Get all metadata field values for a resource.',
        'synonyms' => ['metadata', 'fields', 'values'],
        'readOnlyHint' => true,
        'destructiveHint' => false,
    ],
    'put_resource_data' => [
        'category' => 'resources',
        'description' => 'Update columns on the resource table record.',
        'synonyms' => ['update', 'resource', 'record'],
        'readOnlyHint' => false,
        'destructiveHint' => false,
    ],
    'delete_resource' => [
        'category' => 'resources',
        'description' => 'Delete a resource and its files.',
        'synonyms' => ['delete', 'remove', 'destroy'],
        'readOnlyHint' => false,
        'destructiveHint' => true,
    ],
    'copy_resource' => [
        'category' => 'resources',
        'description' => 'Copy a resource, optionally changing its type.',
        'synonyms' => ['duplicate', 'clone', 'copy'],
        'readOnlyHint' => false,
        'destructiveHint' => false,
    ],
    'upload_file' => [
        'category' => 'resources',
        'description' => 'Attach a local file path as the resource original.',
        'synonyms' => ['upload', 'file', 'attach'],
        'readOnlyHint' => false,
        'destructiveHint' => false,
    ],
    'upload_file_by_url' => [
        'category' => 'resources',
        'description' => 'Attach a file from a URL as the resource original.',
        'synonyms' => ['upload', 'url', 'file'],
        'readOnlyHint' => false,
        'destructiveHint' => false,
    ],
    'upload_multipart' => [
        'category' => 'resources',
        'description' => 'Upload a multipart file as the original, preview, or alternative.',
        'synonyms' => ['upload', 'multipart', 'file'],
        'readOnlyHint' => false,
        'destructiveHint' => false,
    ],
    'replace_resource_file' => [
        'category' => 'resources',
        'description' => 'Replace the original file from a path or URL.',
        'synonyms' => ['replace', 'file', 'original'],
        'readOnlyHint' => false,
        'destructiveHint' => false,
    ],
    'add_alternative_file' => [
        'category' => 'resources',
        'description' => 'Add an alternative file to a resource.',
        'synonyms' => ['alternative', 'attach', 'file'],
        'readOnlyHint' => false,
        'destructiveHint' => false,
    ],
    'delete_alternative_file' => [
        'category' => 'resources',
        'description' => 'Delete an alternative file from a resource.',
        'synonyms' => ['delete', 'alternative', 'remove'],
        'readOnlyHint' => false,
        'destructiveHint' => true,
    ],
    'get_alternative_files' => [
        'category' => 'resources',
        'description' => 'List alternative files attached to a resource.',
        'synonyms' => ['alternatives', 'files', 'list'],
        'readOnlyHint' => true,
        'destructiveHint' => false,
    ],
    'get_related_resources' => [
        'category' => 'resources',
        'description' => 'List resources related to a given resource.',
        'synonyms' => ['related', 'linked', 'resources'],
        'readOnlyHint' => true,
        'destructiveHint' => false,
    ],
    'update_related_resource' => [
        'category' => 'resources',
        'description' => 'Add or remove related-resource links.',
        'synonyms' => ['relate', 'link', 'unlink'],
        'readOnlyHint' => false,
        'destructiveHint' => false,
    ],
    'relate_all_resources' => [
        'category' => 'resources',
        'description' => 'Relate every resource in a set to the others.',
        'synonyms' => ['relate', 'all', 'link'],
        'readOnlyHint' => false,
        'destructiveHint' => false,
    ],
    'get_resource_log' => [
        'category' => 'resources',
        'description' => 'Get the activity log for a resource.',
        'synonyms' => ['log', 'history', 'audit'],
        'readOnlyHint' => true,
        'destructiveHint' => false,
    ],
    'resource_log_last_rows' => [
        'category' => 'resources',
        'description' => 'Return recent resource-log rows across the system.',
        'synonyms' => ['log', 'recent', 'audit'],
        'readOnlyHint' => true,
        'destructiveHint' => false,
    ],
    'get_resource_path' => [
        'category' => 'resources',
        'description' => 'Get a file or preview URL for a resource size.',
        'synonyms' => ['path', 'url', 'preview'],
        'readOnlyHint' => true,
        'destructiveHint' => false,
    ],
    'get_resource_all_image_sizes' => [
        'category' => 'resources',
        'description' => 'List available image sizes and URLs for a resource.',
        'synonyms' => ['sizes', 'previews', 'images'],
        'readOnlyHint' => true,
        'destructiveHint' => false,
    ],
    'get_data_by_field' => [
        'category' => 'resources',
        'description' => 'Get one metadata field value for a resource.',
        'synonyms' => ['field', 'value', 'metadata'],
        'readOnlyHint' => true,
        'destructiveHint' => false,
    ],
    'update_resource_type' => [
        'category' => 'resources',
        'description' => 'Change the resource type of a resource.',
        'synonyms' => ['type', 'update', 'resource'],
        'readOnlyHint' => false,
        'destructiveHint' => false,
    ],
    'get_resource_types' => [
        'category' => 'resources',
        'description' => 'List configured resource types.',
        'synonyms' => ['types', 'schema', 'list'],
        'readOnlyHint' => true,
        'destructiveHint' => false,
    ],
    'resource_file_readonly' => [
        'category' => 'resources',
        'description' => 'Report whether the resource original file is read-only.',
        'synonyms' => ['readonly', 'file', 'lock'],
        'readOnlyHint' => true,
        'destructiveHint' => false,
    ],
    'get_edit_access' => [
        'category' => 'resources',
        'description' => 'Return whether the current user can edit a resource.',
        'synonyms' => ['edit', 'access', 'permission'],
        'readOnlyHint' => true,
        'destructiveHint' => false,
    ],
    'get_resource_access' => [
        'category' => 'resources',
        'description' => 'Return the current user access level for a resource.',
        'synonyms' => ['access', 'permission', 'confidential'],
        'readOnlyHint' => true,
        'destructiveHint' => false,
    ],
    'delete_resources_in_collection' => [
        'category' => 'resources',
        'description' => 'Delete every resource that is in a collection.',
        'synonyms' => ['delete', 'collection', 'bulk'],
        'readOnlyHint' => false,
        'destructiveHint' => true,
    ],
    'get_processing_message' => [
        'category' => 'resources',
        'description' => 'Get the current processing-status message.',
        'synonyms' => ['processing', 'status', 'progress'],
        'readOnlyHint' => true,
        'destructiveHint' => false,
    ],
    'delete_access_keys' => [
        'category' => 'resources',
        'description' => 'Delete resource or collection external-share access keys.',
        'synonyms' => ['delete', 'share', 'keys'],
        'readOnlyHint' => false,
        'destructiveHint' => true,
    ],
    'create_collection' => [
        'category' => 'collections',
        'description' => 'Create a collection owned by the current user.',
        'synonyms' => ['album', 'set', 'new'],
        'readOnlyHint' => false,
        'destructiveHint' => false,
    ],
    'delete_collection' => [
        'category' => 'collections',
        'description' => 'Delete a collection the user can write to.',
        'synonyms' => ['delete', 'remove', 'album'],
        'readOnlyHint' => false,
        'destructiveHint' => true,
    ],
    'add_resource_to_collection' => [
        'category' => 'collections',
        'description' => 'Add one resource to a collection.',
        'synonyms' => ['add', 'collection', 'membership'],
        'readOnlyHint' => false,
        'destructiveHint' => false,
    ],
    'collection_add_resources' => [
        'category' => 'collections',
        'description' => 'Add multiple resources to a collection.',
        'synonyms' => ['add', 'bulk', 'collection'],
        'readOnlyHint' => false,
        'destructiveHint' => false,
    ],
    'remove_resource_from_collection' => [
        'category' => 'collections',
        'description' => 'Remove one resource from a collection.',
        'synonyms' => ['remove', 'collection', 'membership'],
        'readOnlyHint' => false,
        'destructiveHint' => true,
    ],
    'collection_remove_resources' => [
        'category' => 'collections',
        'description' => 'Remove multiple resources from a collection.',
        'synonyms' => ['remove', 'bulk', 'collection'],
        'readOnlyHint' => false,
        'destructiveHint' => true,
    ],
    'get_user_collections' => [
        'category' => 'collections',
        'description' => 'List collections owned by or visible to the current user.',
        'synonyms' => ['my', 'collections', 'list'],
        'readOnlyHint' => true,
        'destructiveHint' => false,
    ],
    'search_public_collections' => [
        'category' => 'collections',
        'description' => 'Search public and featured collections.',
        'synonyms' => ['public', 'featured', 'search'],
        'readOnlyHint' => true,
        'destructiveHint' => false,
    ],
    'get_resource_collections' => [
        'category' => 'collections',
        'description' => 'List collections that contain a resource.',
        'synonyms' => ['membership', 'collections', 'resource'],
        'readOnlyHint' => true,
        'destructiveHint' => false,
    ],
    'get_collection' => [
        'category' => 'collections',
        'description' => 'Get a collection record by reference.',
        'synonyms' => ['collection', 'record', 'details'],
        'readOnlyHint' => true,
        'destructiveHint' => false,
    ],
    'save_collection' => [
        'category' => 'collections',
        'description' => 'Update allowed collection properties such as name and users.',
        'synonyms' => ['save', 'update', 'collection'],
        'readOnlyHint' => false,
        'destructiveHint' => false,
    ],
    'get_featured_collections' => [
        'category' => 'collections',
        'description' => 'List featured collections under a parent.',
        'synonyms' => ['featured', 'themes', 'browse'],
        'readOnlyHint' => true,
        'destructiveHint' => false,
    ],
    'reorder_featured_collections' => [
        'category' => 'collections',
        'description' => 'Reorder featured collections.',
        'synonyms' => ['reorder', 'featured', 'themes'],
        'readOnlyHint' => false,
        'destructiveHint' => false,
    ],
    'show_hide_collection' => [
        'category' => 'collections',
        'description' => 'Show or hide a collection for a user.',
        'synonyms' => ['hide', 'show', 'visibility'],
        'readOnlyHint' => false,
        'destructiveHint' => false,
    ],
    'send_collection_to_admin' => [
        'category' => 'collections',
        'description' => 'Submit a collection to administrators.',
        'synonyms' => ['submit', 'admin', 'collection'],
        'readOnlyHint' => false,
        'destructiveHint' => false,
    ],
    'get_collections_resource_count' => [
        'category' => 'collections',
        'description' => 'Count resources in readable collections.',
        'synonyms' => ['count', 'size', 'collections'],
        'readOnlyHint' => true,
        'destructiveHint' => false,
    ],
    'get_field_options' => [
        'category' => 'metadata',
        'description' => 'List options for a metadata field.',
        'synonyms' => ['options', 'nodes', 'choices'],
        'readOnlyHint' => true,
        'destructiveHint' => false,
    ],
    'update_field' => [
        'category' => 'metadata',
        'description' => 'Update one metadata field value on a resource.',
        'synonyms' => ['tag', 'field', 'value'],
        'readOnlyHint' => false,
        'destructiveHint' => false,
    ],
    'get_nodes' => [
        'category' => 'metadata',
        'description' => 'List nodes for a fixed-list metadata field.',
        'synonyms' => ['nodes', 'keywords', 'tree'],
        'readOnlyHint' => true,
        'destructiveHint' => false,
    ],
    'set_node' => [
        'category' => 'metadata',
        'description' => 'Create or update a metadata node.',
        'synonyms' => ['node', 'keyword', 'create'],
        'readOnlyHint' => false,
        'destructiveHint' => false,
    ],
    'add_resource_nodes' => [
        'category' => 'metadata',
        'description' => 'Add nodes to a resource.',
        'synonyms' => ['nodes', 'tag', 'add'],
        'readOnlyHint' => false,
        'destructiveHint' => false,
    ],
    'add_resource_nodes_multi' => [
        'category' => 'metadata',
        'description' => 'Add nodes to multiple resources.',
        'synonyms' => ['nodes', 'bulk', 'tag'],
        'readOnlyHint' => false,
        'destructiveHint' => false,
    ],
    'get_node_id' => [
        'category' => 'metadata',
        'description' => 'Resolve a node name to its ID in a field.',
        'synonyms' => ['node', 'id', 'lookup'],
        'readOnlyHint' => true,
        'destructiveHint' => false,
    ],
    'toggle_active_state_for_nodes' => [
        'category' => 'metadata',
        'description' => 'Toggle whether listed nodes are active.',
        'synonyms' => ['nodes', 'active', 'toggle'],
        'readOnlyHint' => false,
        'destructiveHint' => false,
    ],
    'get_resource_type_fields' => [
        'category' => 'metadata',
        'description' => 'List metadata fields, optionally filtered by type.',
        'synonyms' => ['fields', 'schema', 'list'],
        'readOnlyHint' => true,
        'destructiveHint' => false,
    ],
    'create_resource_type_field' => [
        'category' => 'metadata',
        'description' => 'Create a metadata field.',
        'synonyms' => ['field', 'create', 'schema'],
        'readOnlyHint' => false,
        'destructiveHint' => false,
    ],
    'save_tab' => [
        'category' => 'metadata',
        'description' => 'Create or update a metadata tab.',
        'synonyms' => ['tab', 'save', 'metadata'],
        'readOnlyHint' => false,
        'destructiveHint' => false,
    ],
    'reorder_tabs' => [
        'category' => 'metadata',
        'description' => 'Reorder metadata tabs.',
        'synonyms' => ['tabs', 'reorder', 'order'],
        'readOnlyHint' => false,
        'destructiveHint' => false,
    ],
    'delete_tabs' => [
        'category' => 'metadata',
        'description' => 'Delete metadata tabs.',
        'synonyms' => ['tabs', 'delete', 'remove'],
        'readOnlyHint' => false,
        'destructiveHint' => true,
    ],
    'checkperm' => [
        'category' => 'users',
        'description' => 'Check whether the current user has a permission code.',
        'synonyms' => ['permission', 'access', 'capability'],
        'readOnlyHint' => true,
        'destructiveHint' => false,
    ],
    'get_users' => [
        'category' => 'users',
        'description' => 'Search users and return non-sensitive profile fields.',
        'synonyms' => ['users', 'accounts', 'search'],
        'readOnlyHint' => true,
        'destructiveHint' => false,
    ],
    'new_user' => [
        'category' => 'users',
        'description' => 'Create a user account.',
        'synonyms' => ['account', 'create', 'user'],
        'readOnlyHint' => false,
        'destructiveHint' => true,
    ],
    'save_user' => [
        'category' => 'users',
        'description' => 'Save an existing user account.',
        'synonyms' => ['account', 'update', 'user'],
        'readOnlyHint' => false,
        'destructiveHint' => true,
    ],
    'get_users_by_permission' => [
        'category' => 'users',
        'description' => 'List users who have given permission codes.',
        'synonyms' => ['users', 'permission', 'filter'],
        'readOnlyHint' => true,
        'destructiveHint' => false,
    ],
    'send_user_message' => [
        'category' => 'users',
        'description' => 'Send a user-to-user message.',
        'synonyms' => ['message', 'notify', 'send'],
        'readOnlyHint' => false,
        'destructiveHint' => false,
    ],
    'get_user_message' => [
        'category' => 'users',
        'description' => 'Get a user message by reference.',
        'synonyms' => ['message', 'inbox', 'read'],
        'readOnlyHint' => true,
        'destructiveHint' => false,
    ],
    'get_profile_image' => [
        'category' => 'users',
        'description' => 'Get a user profile image URL.',
        'synonyms' => ['avatar', 'profile', 'image'],
        'readOnlyHint' => true,
        'destructiveHint' => false,
    ],
    'mark_email_as_invalid' => [
        'category' => 'users',
        'description' => 'Mark an email address as invalid.',
        'synonyms' => ['email', 'invalid', 'bounce'],
        'readOnlyHint' => false,
        'destructiveHint' => true,
    ],
    'get_system_status' => [
        'category' => 'system',
        'description' => 'Return installation and dependency status checks.',
        'synonyms' => ['health', 'status', 'checks'],
        'readOnlyHint' => true,
        'destructiveHint' => false,
    ],
    'get_daily_stat_summary' => [
        'category' => 'system',
        'description' => 'Summarise daily activity statistics for recent days.',
        'synonyms' => ['stats', 'activity', 'summary'],
        'readOnlyHint' => true,
        'destructiveHint' => false,
    ],

    'magnolia_query_activity_log' => [
        'category' => 'plugins',
        'description' => 'Query activity_log for Traffic/ops (user, note_like, America/Chicago month_year).',
        'synonyms' => ['activity', 'log', 'traffic', 'api search', 'ops'],
        'readOnlyHint' => true,
        'destructiveHint' => false,
    ],
    'magnolia_query_search_log' => [
        'category' => 'plugins',
        'description' => 'Query search_log for Traffic/ops (user, America/Chicago month_year).',
        'synonyms' => ['search', 'log', 'traffic', 'ops'],
        'readOnlyHint' => true,
        'destructiveHint' => false,
    ],
];
